PDA/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from accounts import views
from PDA import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.user_login,name='user_login'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^predict/',include('generate.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
#url(r'^profile/(?P<pk>\d+)/edit/$', views.profile_update, name='edit_profile'),
]

generate/urls.py
from django.conf.urls import url
from . import views
app_name='predict'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk,name='predict')
]

generate/models.py
from django.db import models
from accounts.models import UserProfileInfo
from django.utils import timezone
from django.urls import reverse
# Create your models here.


class Predictions(models.Model):
    profile = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE, related_name='predict')
    filename = models.CharField(max_length = 200,default="CFG.py")



    def get_absolute_url(self):
        return reverse('predict:predict', kwargs={'pk': self.profile.pk})

generate/forms.py
from django import forms
from generate.models import Predictions

class Predict_Form(forms.ModelForm):
    class Meta:
        model = Predictions
        fields = ('filename',)
        widgets = {'filename': forms.TextInput(attrs={'class': 'form-control'}),
                   #  'CFG_image': forms.ImageField(max_length=20),
                   # 'PDA_image': forms.ImageField(max_length=20),
                   # 'SCC_image': forms.ImageField(max_length=20),

                   }

generate/views.py
import csv,io
from django.shortcuts import render
from .forms import Predict_Form

from accounts.models import UserProfileInfo
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required,permission_required
from django.urls import reverse
from django.contrib import messages
from generate.P import  Generate

from staticfg import CFGBuilder
from generate.PDA import PDA
from graphviz import Digraph
from itertools import combinations


@login_required(login_url='/')
def PredictRisk(request,pk):
    predicted = False
    predictions={}
    if request.session.has_key('user_id'):
        u_id = request.session['user_id']

    if request.method == 'POST':
        form = Predict_Form(data=request.POST)
        profile = get_object_or_404(UserProfileInfo, pk=pk)

        if form.is_valid():


            print("Before------")
            generator_temp=Generate('CFG.py')
            generator_temp.build_Path(generator_temp.cfg,1)


            print("Hell0-------")




            pred = form.save(commit=False)





            pred.profile = profile

            pred.save()
            predicted = True



    if predicted:
        return render(request, 'predict.html',
                      {'form': form,'predicted': predicted,'user_id':u_id,'predictions':predictions})

    else:
        form = Predict_Form()

        return render(request, 'predict.html',
                      {'form': form,'predicted': predicted,'user_id':u_id,'predictions':predictions})

generate/templates/predict.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
<title>Generate PDA page</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="{% static 'css/style2.css' %}" rel="stylesheet" />

<link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
<link href="{% static 'css/medium-editor.min.css' %}" rel="stylesheet">
<!--//fonts-->
</head>
<body style="background-image: url('{% static 'images/3.jpg' %}')">
<!--background-->
<nav class="navbar navbar-expand-lg navbar-transparent" >
        <div class="container">
            <div class="collapse navbar-collapse justify-content-end" id="navigation" >
                <ul class="navbar-nav nav-tabs">

                    <li class="nav-item"><a href="{% url 'accounts:profile' pk=user_id %}" class="btn btn-neutral">Profile</a></li>
                      <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-neutral">Logout</a></li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="bg-agile">
	<div class="book-appointment">
	<h2>Information</h2>

  {% if predicted %}
<div class="card" role="alert">

<div class="card-body">
      <div class="table-responsive justify-content-center">
                       <table class="table">
                           <thead>
                               <tr>
                                   <th>Output</th>
                                   <th>Generated in local please check it</th>
                               </tr>
                           </thead>


                       </table>
                   </div>
               </div>
             </div>

  {% endif %}

			<form method="post">
        {% csrf_token %}
        <div class="center-agileits-w3layouts same">
          <div class="gaps">
            <p>filename<p>
            {{form.filename}}
          </div>

         </div>

				<div class="clear"></div>
				<input type="submit" value="Generate" class="btn btn-primary">
			</form>
		</div>
   </div>
   <!--copyright-->

		<!--//copyright-->
		<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
		<!-- Calendar -->
				<link rel="stylesheet" href="css/jquery-ui.css" />
				<script src="js/jquery-ui.js"></script>

			<!-- //Calendar -->

</body>
</html>